targets:
  - name: staging
    args:
      environment: staging
      environmentType: non-prod
    # Adding a context to .kluctl.yaml helps prevent accidentally deploying to the wrong cluster!
    context: web-app-project

  - name: production
    args:
      environment: production
      environmentType: prod
    # Adding a context to .kluctl.yaml helps prevent accidentally deploying to the wrong cluster!
    context: gke_web-app-project-007_us-central1-a_web-app-project

args:
  - name: environment
  - name: environmentType

discriminator: kluctl-{{ target.name }}
