apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: web-app
  namespace: kluctl-gitops
spec:
  interval: 5m
  source:
    git:
      url: https://github.com/Adeniyilowee/Web-App-on-GKE.git
      path: deployment-env/kluctl
  target: staging
  context: default
  # let it automatically clean up orphan KluctlDeployment resources
  prune: true
  delete: true
