# 🚨 This is currently unused (for example purposes)
# The env var is defined directly in the deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: load-generator-config
  namespace: web-app
data:
  API_URL: http://api-node.web-app.svc.cluster.local:3000
  DELAY_MS: "100"
